version: '3'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./heart.csv:/tmp/heart.csv  # Mount the data file
    environment:
      - CLUSTER_NAME=test-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - namenode
      - datanode1
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - namenode
      - datanode1
      - resourcemanager
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    ports:
      - 8188:8188
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - namenode
      - datanode1
      - resourcemanager
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: heart_analysis_webapp
    ports:
      - "5000:5000"
    volumes:
      - ./webapp:/app
    environment:
      - HDFS_NAMENODE_URL=http://namenode:9870
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - namenode
      - datanode1
    networks:
      - hadoop_network

volumes:
  hadoop_namenode:
  hadoop_datanode1:

networks:
  hadoop_network:
    driver: bridge