apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: borrow
  name: borrow
spec:
  ports:
    - name: "5008"
      port: 5008
      targetPort: 5008
  selector:
    io.kompose.service: borrow
