services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - my-network

  userservice:
    build:
      context: ./userservice
    container_name: user
    ports:
      - "5002:5002"
    depends_on:
      - database
    networks:
      - my-network

  # Uncomment and configure if you want to use bookservice
  # bookservice:
  #   build:
  #     context: ./Book
  #   container_name: book
  #   networks:
  #     - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db-data:
